---
name: 'Installs Hoverfly'
description: >
  Installs Hoverfly (https://docs.hoverfly.io),
  so that other GitHub Actions can use it easily (e.g. for testing)
author: 'John Boyes'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
branding:
  icon: 'play'
  color: 'blue'
