---
name: 'Check commit message style'
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches-ignore:
      - '*dependabot/github_actions/*'
  push:
    branches-ignore:
      - '*dependabot/github_actions/*'

jobs:
  check-commit-message-style:
    name: Check commit message style
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mristin/opinionated-commit-message@v2.1.0
        with:
          allow-one-liners: 'true'
