---
name: Dependabot hack
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-hack-workflow

jobs:

  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: ubuntu-latest
    steps:

      # update the version manually in these places, too:
      #   - the default version in `action.yml`
      #   - the example version in the README
      #   - the latest version in the 'tests.yml'
      - uses: SpectoLabs/hoverfly@v1.2.0

      # update the version in `check_semver_labels.yml` manually, too
      # (eventually Dependabot will do this automatically and I won't need this hack)
      - uses: agilepathway/label-checker@v1.0.9

      # update the version in the devcontainer `Dockerfile` manually, too
      - uses: koalaman/shellcheck@v0.7.0

      # update the version in `github_tag_and_release.yml` manually, too
      - uses: golang/go@go1.14.6
