---
# See ../DEPENDENCIES.md#workaround-for-other-dependencies
name: Dependabot hack
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - never-trigger-this-dependabot-hack-workflow

jobs:

  dependabot_hack:
    name: Ensure dependabot version checks
    runs-on: ubuntu-latest
    steps:

      # update the version manually in these places, too:
      #   - the default version in `action.yml`
      #   - the example versions in the README (3 places)
      #   - the latest version in the 'test.yml'
      - uses: SpectoLabs/hoverfly@v1.11.3

      # update the version in `check_semver_labels.yml` manually, too
      # (eventually Dependabot will do this automatically and I won't need this hack)
      - uses: agilepathway/label-checker@v1.6.65

      # update the version in `github_tag_and_release.yml` manually, too
      - uses: golang/go@go1.23.12
