---
name: Release

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - closed

jobs:

  tag:
    name: Tag semantic version
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@v1.3.1
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: tag
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 1.15
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
